# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname bind_condition2parameters_r
#' @export
split_parameter_x_condition <- function(parameter_M_r) {
    .Call(`_ggdmcModel_split_parameter_x_condition`, parameter_M_r)
}

#' @rdname parameter_mapping_functions
#' @export
is_core_parameter_x_condition <- function(parameter_map_r, factors_r) {
    .Call(`_ggdmcModel_is_core_parameter_x_condition`, parameter_map_r, factors_r)
}

#' @rdname parameter_mapping_functions
#' @export
is_parameter_x_condition <- function(parameter_map_r, factors_r) {
    .Call(`_ggdmcModel_is_parameter_x_condition`, parameter_map_r, factors_r)
}

#' @rdname parameter_mapping_functions
#' @export
get_stimulus_level_r <- function(parameter_map_r, factors_r, accumulators_r) {
    .Call(`_ggdmcModel_get_stimulus_level_r`, parameter_map_r, factors_r, accumulators_r)
}

#' @rdname parameter_mapping_functions
#' @export
get_factor_cells_r <- function(parameter_map_r, factors_r, accumulators_r) {
    .Call(`_ggdmcModel_get_factor_cells_r`, parameter_map_r, factors_r, accumulators_r)
}

#' @rdname model_parameter_utils
#' @export
table_parameters <- function(model_r, parameters_r) {
    .Call(`_ggdmcModel_table_parameters`, model_r, parameters_r)
}

#' @rdname model_parameter_utils
#' @export
print_parameter_map <- function(model_r) {
    .Call(`_ggdmcModel_print_parameter_map`, model_r)
}

#' @rdname build_cell_names_r
#' @export
build_cell_names_r <- function(parameter_map_r, factors_r = NULL, accumulators_r = NULL) {
    .Call(`_ggdmcModel_build_cell_names_r`, parameter_map_r, factors_r, accumulators_r)
}

#' @rdname build_model_boolean_r
#' @export
build_model_boolean_r <- function(parameter_map_r, factors_r = NULL, accumulators_r = NULL, match_map_r = NULL) {
    .Call(`_ggdmcModel_build_model_boolean_r`, parameter_map_r, factors_r, accumulators_r, match_map_r)
}

#' @export
bind_condition2parameters_r <- function(parameter_map_r, factors_r = NULL) {
    .Call(`_ggdmcModel_bind_condition2parameters_r`, parameter_map_r, factors_r)
}

#' Get Index Mapping for the Node 1 Accumulator
#'
#' @description
#' Generates an integer matrix mapping experimental design cells to their
#' corresponding indexes of the node 1 accumulator. The node 1 accumulator
#' is the theoretical accumulator that reaches the threshold first. This
#' function is primarily used for the LBA model.
#'
#' @param parameter_map_r An Rcpp::List where each element is a character
#' vector mapping parameters to conditions. Names should correspond to
#' parameters.
#' @param factors_r An Rcpp::List where each element is a character
#' vector of factor levels. Names should correspond to factor names.
#' @param accumulators_r A character vector of response accumulator names.
#'
#' @return An integer matrix with dimensions:
#' \itemize{
#'   \item Rows: Experimental conditions (cells)
#'   \item Columns: Accumulators (responses)
#' }
#' Where values represent parameter indices for each condition-response
#' combination.
#'
#' @details
#' The function:
#' \enumerate{
#'   \item Computes node indices for each condition-response pair
#'   \item Returns results as an R-compatible integer matrix
#' }
#'
#' @examples
#' cat("Flexible stimulus name")
#' p_map <- list(A = "1", B = "S", t0 = "E", mean_v = c("D", "M"),
#'                sd_v = "M", st0 = "1")
#' factors <- list(S = c("sti_1", "sti_2", "sti_3", "sti_4"),
#'                 D = c("d1", "d2"), E = c("e1", "e2"))
#' responses <- c("resp_1", "resp_2", "resp_3", "resp_4")
#'
#' # Get node indices
#' result <- get_node_1_index_r(p_map, factors, responses)
#' print(dim(result)[[1]])
#' # 64
#'
#' @export
get_node_1_index_r <- function(parameter_map_r, factors_r, accumulators_r) {
    .Call(`_ggdmcModel_get_node_1_index_r`, parameter_map_r, factors_r, accumulators_r)
}

#' @rdname get_pnames
#' @export
get_pnames <- function(model_r, debug = FALSE) {
    .Call(`_ggdmcModel_get_pnames`, model_r, debug)
}

